# Generated by Django 4.2.11 on 2025-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='a.png', upload_to='upload')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
